### ISSUE TITLE
bug: Parsing fails for setup.cfg files

### ISSUE THREAD

**Issue by ZryletTC** [pyupio/dparse#84]
# Bug Report

**dparse version:**
0.6.4

**Current behavior:**
Parsing a setup.cfg file current yields:
```
AttributeError: 'str' object has no attribute 'name'
```

**Expected behavior:**
I expected no errors and successful reading of setup.cfg files.

**Steps to reproduce:**
```
from dparse import parse
parse(content, file_type=("setup.cfg"))
```

**Related code:**
Broken by 5b9cb59 because the merge excluded a crucial change from bd34a60:
```diff
-           if section.name == 'options':
+            if section == 'options':
```
